apiVersion: apps/v1
kind: Deployment
metadata:
  name: gndemo-deployment
  labels:
    app: gndemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gndemo
  template:
    metadata:
      labels:
        app: gndemo
    spec:
      containers:
      - name: gndemo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80